server:
  port: ${REGIONS_SERVER_PORT}

spring:
  application:
    name: ${REGIONS_APP_NAME}

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    open-in-view: ${JPA_OPEN_IN_VIEW}

  sql:
    init:
      mode: ${SQL_INIT_MODE}

  flyway:
    enabled: ${FLYWAY_ENABLED}
    locations: ${FLYWAY_LOCATIONS}
    baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE}
    clean-disabled: ${FLYWAY_CLEAN_DISABLED}

regions:
  cacheSeconds: ${REGIONS_CACHE_SECONDS}
